sign-tag = true
consolidate-commits = true
pre-release-commit-message = "[{{crate_name}} version {{version}}"
tag-message = "[{{crate_name}}] version {{version}}"
tag-name = "{{prefix}}{{version}}"
dev-version = false
publish = false
