[book]
authors = ["Rain"]
language = "en"
multilingual = false
src = "src"
theme = "theme"
title = "cargo-nextest"
description = "A next-generation test runner for Rust."

[build]
build-dir = "output"

[output.html]
default-theme = "rust"
# additional-css = ["css/extra.css"]
copy-fonts = false
git-repository-url = "https://github.com/nextest-rs/nextest"
edit-url-template = "https://github.com/nextest-rs/nextest/edit/main/site/{path}"
site-url = "https://nexte.st"
