on:
  push:
    branches:
      - master
      - main

name: Docs

jobs:
  docs:
    name: Build and deploy documentation
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: Build rustdoc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features --workspace
      - name: Install mdbook
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook
          version: 0.4
      - name: Run mdbook
        run: |
          cd book
          mdbook build
      - name: Organize
        run: |
          rm -rf target/gh-pages
          mkdir target/gh-pages
          mv target/doc target/gh-pages/rustdoc
          mv book/book/.nojekyll target/gh-pages
          mv book/book target/gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/gh-pages
